# Sedentary activities
 - sit
 - stand
 - lie
 - watch_tv
 - elevator_up
 - elevator_down
 - sleep

# Walking activities
 - walk
 - walk_up
 - walk_down
 - walk_left
 - walk_right
 - walk_nordic

# Household
 - iron
 - laundry
 - clean
 - vacuum

# Sport/exercise
 - run
 - cycle
 - soccer
 - rope_jump
 - jump

# Other
 - work_computer
 - drive_car

# Catchall
 - other
 - none
